import Footer from '@/components/Footer'
import Register from '@/components/Register'
import Sidebar from '@/components/Sidebar'
import Trends from '@/components/Trends'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='container mx-auto h-screen'>
        <div className="flex h-full">
          <Sidebar />
          <Trends />
          <Register />
        </div>
        <Footer />
      </main>
    </>
  )
}
