import Footer from '@/components/Footer'
import Register from '@/components/Register'
import RegisterModal from '@/components/RegisterModal'
import Sidebar from '@/components/Sidebar'
import Trends from '@/components/Trends'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'


export default function Landing() {
  const initialState = {
    isModalOpen: false,
    newMember: false
  }
  const [details, setDetails ] = useState(initialState)
  
  const { user } = useSelector((store)=>store.auth)
  const router = useRouter()

  useEffect(() => {
    if(user){
      setTimeout(() => {
        setDetails(initialState)
        router.push('/home')
      }, 2000);
    }
    
  }, [ user ])
  

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='max-w-7xl mx-auto h-screen'>
        {details.isModalOpen && <RegisterModal details={details} setDetails={setDetails} />}
        <div className="flex h-full">
          <Sidebar />
          <Trends />
          <Register setDetails={setDetails} details={details}/>
        </div>
        <Footer setDetails={setDetails} details={details}/>
      </main>
    </>
  )
}
